### PR TITLE
Added LesPas

### PR DESCRIPTION
**Pull request by scubajeff**
as requested

### CODE REVIEW

**Comment by meichthys** [comment]
Please don't take my comments critically. I'm just trying to provide the most accurate comparisons.

**Comment by scubajeff** [comment]
What comments? Did I miss something?

**Review by meichthys — CHANGES_REQUESTED** [review]
Oops, i forgot to submit the review. You should see my comments now.

**Comment by scubajeff** [comment]
I did have some difficulties putting down those subjective score. Different product have different design philosophy, and don't even mention comparing a client side solution to server side ones. So, forget it. I will close this one. It's not really the right way to do it IMHO.

**Comment by meichthys** [comment]
I agree that it is difficult to compare different types of solutions which might not always be apples to apples comparisons, but with Nextcloud as a backend, the server side is covered for you 👍

**Pull request closed without merging**
