### PR TITLE
Add "Photo Tagging" row to feature table

### PR DESCRIPTION
**Pull request by Targren**
Took the hint from suggestion issue #41 

Based on what I could glean from demos or local installs. Could not test "Nextcloud Memories".

### CODE REVIEW

**Review by meichthys — COMMENTED** [review]
Looks good so far. Would you be able to provide a subjective rating of how well the tagging feature is implemented? (A score of 1-10).

Could you add a link to the relevant GitHub issues for the projects that are actively working on this feature?

Also, for memories, it can get the same score as nextcloud photos.

**Comment by Targren** [comment]
I'll see what I can do with the ones I can get installed and running locally. The ones I couldn't get working from the demos, I took the projects' feature lists at their word.

It will probably need some tweaking when I'm done though, because my editor is choking on the pretty number boxes the table uses.

**Review by Targren — COMMENTED** [review]
As requested, some entries changed when firsthand testing revealed only AI tags, not user-defined.

**Comment by meichthys** [comment]
> I'll see what I can do with the ones I can get installed and running locally. The ones I couldn't get working from the demos, I took the projects' feature lists at their word.
> 
> It will probably need some tweaking when I'm done though, because my editor (Notepad++) is choking on the pretty number boxes the table uses.

Yes, this is fine. I often cannot test all of them, so i take the marketing at face value until otherwise shown to be different.

**Review by meichthys — APPROVED** [review]

**Comment by meichthys** [comment]
Thanks for putting this together!

**Pull request merged**
